// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;

namespace Cineworld
{

    public partial class Person
    {
        public class Credits2
        {

            [JsonProperty("cast")]
            public Cast2[] Cast { get; set; }

            [JsonProperty("crew")]
            public Crew2[] Crew { get; set; }
        }
    }

}
