// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;

namespace Cineworld
{

    public class FilmImages
    {

        [JsonProperty("id")]
        public int Id { get; set; }

        [JsonProperty("backdrops")]
        public Backdrop[] Backdrops { get; set; }

        [JsonProperty("posters")]
        public Poster[] Posters { get; set; }
    }

}
