// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;
using System.Globalization;

namespace Cineworld
{

	public class MovieCastInfo
    {
        public string Title { get; set; }

        public string Character { get; set; }

        public Uri PosterUrl { get; set; }

        public string ReleaseDate { get; set; }

        public MovieCastInfo(string baseUrl, string size, Person.Cast2 cast)
        {
            this.Title = cast.Title;
            this.Character = cast.Character;

            try
            {
                DateTime dtRelease = DateTime.MinValue;

                if(!String.IsNullOrWhiteSpace(cast.ReleaseDate))
                    dtRelease = DateTime.ParseExact(cast.ReleaseDate, "yyyy-MM-dd", CultureInfo.InvariantCulture);

                if (dtRelease != DateTime.MinValue)
                    this.ReleaseDate = dtRelease.ToString("dd MMM yyyy");
            }
            catch { }

            if (!String.IsNullOrWhiteSpace(cast.PosterPath))
                this.PosterUrl = new Uri(String.Format("{0}{1}{2}", baseUrl, size, cast.PosterPath));
        }
    }

}
